/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebarMain: [
    'information/intro',
    'information/faq',
    {
      type: 'category',
      label: 'The Basics',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'information/basics'},
      ]
    },
    {
      type: 'category',
      label: 'Dive Deeper',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'information/core-concepts'},
      ]
    },
    {
      type: 'category',
      label: 'Fees',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'information/fees'},
      ]
    },
    'information/partnerships',
    {
      type: 'category',
      label: 'Others',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'information/resources'},
        {type: 'link', label: 'Content Repository', href: 'https://www.notion.so/pendle/Resources-fe1f22082404477b8e1c591497d49247'},
      ]
    }
  ],
  sidebarGuides: [
    'guides/intro',
    'guides/tokenizing-yield-tokens',
    'guides/performing-a-swap',
    'guides/provisioning-liquidity',
  ],
  sidebarAddresses: [
    'addresses/mainnet',
    'addresses/kovan',
  ],
  sidebarReference: [
    'reference/intro',
    {
      type: 'category',
      label: 'Contracts',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'reference/contracts'},
      ]
    },
    'reference/sdk',
    'reference/subgraph',
  ],
};
