module.exports = {
  myAutogeneratedSidebar: [
    {
      type: "doc",
      id: "Home",
      label: "Home",
    },
    {
      type: "doc",
      id: "Introduction",
      label: "Introduction",
    },
    {
      type: "link",
      label: "Learn",
      href: 'https://app.pendle.finance/pro/learn',
    },
    {
      type: "doc",
      id: "FAQ/General",
      label: "FAQ",
    },
    {
      type: "link",
      label: "Whitepapers",
      href: 'https://github.com/pendle-finance/pendle-v2-resources/tree/main/whitepapers',
    },
    {
      type: "category",
      label: "Using Pendle",
      items: [
        { type: "doc", id: "UsingPendle/Simple" },
        { type: "doc", id: "UsingPendle/Discount" },
        { type: "doc", id: "UsingPendle/Pools" },
        { type: "doc", id: "UsingPendle/Dashboard" },
      ],
    },
    {
      type: "category",
      label: "Pendle Pro",
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "PendlePro/UsingPro"
        },
        {
          type: "category",
          label: "Guides",
          collapsed: true,
          items: [
            { type: "doc", id: "PendlePro/Guides/Mint" },
            { type: "doc", id: "PendlePro/Guides/Swap" },
            { type: "doc", id: "PendlePro/Guides/Farm" },
            { type: "doc", id: "PendlePro/Guides/Claim" },
            { type: "doc", id: "PendlePro/Guides/CreatingNewPools" },
            { type: "doc", id: "PendlePro/Guides/UnwrappingSY" },
          ],
        },
        {
          type: "category",
          label: "How it Works",
          collapsed: true,
          items: [
            { type: "doc", id: "PendlePro/HowItWorks/SY" },
            { type: "doc", id: "PendlePro/HowItWorks/AMM" },
            { type: "doc", id: "PendlePro/HowItWorks/Fees" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Governance",
      collapsed: true,
      items: [
        { type: "doc", id: "Governance/PENDLE", label: "PENDLE" },
        { type: "doc", id: "Governance/PENDLEnomics", label: "PENDLEnomics" },
        { type: "doc", id: "Governance/vePENDLE", label: "vePENDLE" },
        {
          type: "category",
          label: "Guides",
          collapsed: true,
          items: [
            { type: "doc", id: "Governance/Guides/Lock" },
            { type: "doc", id: "Governance/Guides/ClaimRewards" },
            {
              type: "doc",
              id: "Governance/Guides/ChannelIncentives",
            },
            { type: "doc", id: "Governance/Guides/ApplyBoost" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Developers",
      items: [
        {
          type: "category",
          label: "Deployed Contracts",
          items: [
            { type: "doc", id: "Developers/DeployedContracts/Ethereum" },
          ],
        },
        { type: "doc", id: "Developers/SDK" },
      ],
    },
  ],
};
